### PR TITLE
Add overall conduct introduction

### PR DESCRIPTION
**Pull request by DlHolland**
## Description

Added an introduction to overall conduct.

### Type of Change

- [X] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @DlHolland 

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

### CODE REVIEW

**Review by Jacob-Allebach — DISMISSED** [review]
Looks great! :shipit:

**Comment by mariakimheinert** [comment]
@DlHolland, what do you think about adding the details I mentioned in PR https://github.com/Jacob-Allebach/code-of-conduct/pull/15#issuecomment-1062126530?

**Comment by DlHolland** [comment]
> @DlHolland, what do you think about adding the details I mentioned in PR [#15 (comment)](https://github.com/Jacob-Allebach/code-of-conduct/pull/15#issuecomment-1062126530)?

That's an excellent suggestion, thank you!  I forgot we'd discussed ideas for the intro in the earlier issue, I'll make the changes.

**Comment by DlHolland** [comment]
I reworked the introduction adding in the suggestions Maria made from the other issue tracker.  Let me know if anything needs to be changed!

**Review by Jacob-Allebach — APPROVED** [review]
I like the changes, think it's good 👍

**Review by Ochirsaikhan — APPROVED** [review]
The edited version looks better.

**Pull request merged**
