### PR TITLE
Define acceptable postmortems

### PR DESCRIPTION
**Pull request by DlHolland**
## Description

Added acceptable postmortems
### Type of Change

- [X] Feature
- [ ] Bug fix
- [x] Documentation

## Contributors

- @DlHolland 

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

### CODE REVIEW

**Review by Ochirsaikhan — CHANGES_REQUESTED** [review]
For the first point, I think it would make sense to change the part "right/wrong" to "right or wrong" for formatting consistency. Other than that, it looks good!

**Review by Ochirsaikhan — APPROVED** [review]
Looks good 👌

**Review by PaigeCD — APPROVED** [review]
This looks good to me! :+1: :sparkles:

**Review by mariakimheinert — APPROVED** [review]
@DlHolland, thanks for adding these changes! They look great! :shipit:

**Review by anthonygc — APPROVED** [review]
Looks good!

**Pull request merged**
